---
# tasks file for common
- name: install updates
  yum:
    name: "*"
    state: latest

- name: Install requirements package
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - curl-devel
    - pexpect
    - httpd-devel
    - apr-devel
    - apr-util-devel
    - expect
