---
# defaults file for apache
server_name: "{{ ansible_nodename }}"
apache_path: '/etc/httpd'
apache_log_dir: '/var/log/httpd'
error_log: "{{ apache_log_dir }}/error_log"

ssl_cert_directory: "{{ apache_path }}/ssl"
apache_certificates:
  ca_cert_src: 'files/ca_cert.pem'
  server_cert_src: 'files/server_cert.pem'
  server_key_src: 'files/server_key.pem'

apache_mods:
  - mod_name: mime_module
    conf_file: mime.conf
    conf_src: "files/mime.conf"
  - mod_name: ssl_module
    conf_file: ssl.conf
    conf_src: "files/ssl.conf"

apache_virtualhosts:
  - file_name: default-vhost-not-secure.conf
    listening_ip: '*'
    listening_port: 80
    server_name: localhost
    document_root: /var/www
    extra_directives: |
      LogLevel info
      ErrorLog {{ apache_log_dir }}/localhost-error.log
      CustomLog {{ apache_log_dir }}/localhost-access.log combined env=!dontlog
      RewriteEngine On
      RewriteCond %{HTTPS} off
      RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
  - file_name: default-vhost-secure.conf
    listening_ip: '*'
    listening_port: 443
    server_name: localhost
    document_root: /var/www
    SSLEngine: "On"
    SSLCACertificateFile: "{{ apache_certificates_dest.ca_cert }}"
    SSLCertificateKeyFile: "{{ apache_certificates_dest.server_key }}"
    SSLCertificateFile: "{{ apache_certificates_dest.server_cert }}"
    _directories:
      - _root: /var/www
        Options: Indexes FollowSymLinks
        AllowOverride: None
        extra_directives: |
          Require all granted
